### ISSUE TITLE
gulp build fails

### ISSUE THREAD

**Issue by songzhou21** [quietshu/ABS-frontend#1]
``` shell
➜  ABS-frontend git:(master) gulp build
[11:13:27] Using gulpfile ~/Developer/gitclone/ABS-frontend/gulpfile.js
[11:13:27] Starting 'usemin'...
[11:13:27] Starting 'copy-fonts'...
[11:13:27] Starting 'copy-fontawesome'...
[11:13:27] Starting 'custom-images'...
[11:13:27] Starting 'custom-js'...
[11:13:27] Starting 'custom-css'...
[11:13:27] Starting 'custom-templates'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Path /Users/song/Developer/gitclone/ABS-frontend/bower_components/fontawesome/css/font-awesome.min.css not found!
    at getFiles (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/lib/blocksBuilder.js:58:15)
    at module.exports (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/lib/blocksBuilder.js:96:20)
    at Transform._transform (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/index.js:16:22)
    at Transform._read (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/song/Developer/gitclone/ABS-frontend/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
➜  ABS-frontend git:(master) tree bower_components/font-awesome/css 
bower_components/font-awesome/css
├── font-awesome.css
└── font-awesome.min.css

0 directories, 2 files

```

已经有 font-awesome.min.css，但还是 build fails 了，是路径错误么？

**Comment by shuding** [comment]
抱歉歉歉歉歉歉！

我把目录名打错了：`font-awesome` → `fontawesome`……马上修复！谢谢！

**Comment by songzhou21** [comment]
谢了
